// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
)

type Channel struct {
	ID              int32
	UserID          int32
	Name            string
	Handle          string
	Description     sql.NullString
	AvatarUrl       sql.NullString
	BannerUrl       sql.NullString
	SubscriberCount sql.NullInt32
	VideoCount      sql.NullInt32
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
}

type User struct {
	ID          int32
	Name        sql.NullString
	Username    string
	Email       string
	Pasword     string
	Country     sql.NullString
	City        sql.NullString
	PhoneNumber sql.NullString
	Age         sql.NullInt32
	AvatarUrl   sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Video struct {
	ID           string
	ChannelID    sql.NullInt32
	Title        string
	Description  sql.NullString
	Likes        sql.NullInt32
	Views        sql.NullInt32
	VideoUrl     string
	ThumbnailUrl sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}
