// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package store

import (
	"context"
	"database/sql"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO video (channel_id, title, description, video_url, thumbnail_url)
VALUES ($1, $2, $3, $4, $5) RETURNING id, channel_id, title, description, likes, views, video_url, thumbnail_url, created_at, updated_at, deleted_at
`

type CreateVideoParams struct {
	ChannelID    sql.NullInt32
	Title        string
	Description  sql.NullString
	VideoUrl     string
	ThumbnailUrl sql.NullString
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo,
		arg.ChannelID,
		arg.Title,
		arg.Description,
		arg.VideoUrl,
		arg.ThumbnailUrl,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.Title,
		&i.Description,
		&i.Likes,
		&i.Views,
		&i.VideoUrl,
		&i.ThumbnailUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
